### ISSUE TITLE
Data doesn't update correctly on 0.9b when loading from savefile

### ISSUE THREAD

**Issue by Algester** [denikson/CM3D2.MaidFiddler#5]
_**EDIT:** Added a more specific description of the issue_

When Maid Fiddler has maids loaded, and a save file with the same maids (but possibly different stats) is loaded, Maid Fiddler does not update the maid list. As a result, Maid Fiddler does not update maid data.

The issue occurs when CM3D2 has a save loaded, Maid Fiddler is closed and another save file is loaded (either through the title screen or the "Load" button).

well not much of a serious bug since... I have pretty much used what I wanted with your plug-in but if other people hasnt reported on what I think it is, it maybe on my side

**Comment by ghorsington** [comment]
What data? What did you try to do?

Could you **elaborate**?
If you don't provide information about the nature of the issue, I really can't look into it and determine whether it is actually due to a bug in the code.

From what I can see, all the basic functionality (like editing basic information) works well.

**Comment by Algester** [comment]
well I can't elaborate further yet either I'm still digging on how to replicate it first
the Data I'm talking about are pretty much the maids' stats for example if I "trained" them the stats dont reflect with the Maid Fiddler
the possible way I think this event happens is when maid fiddler thinks the save data "doesnt load correctly"
IE
when I load and go to the title menu and then load again, since a full restart updated the maids' stats

**Comment by ghorsington** [comment]
My best guess is that either Assembly-CSharp.dll could be improperly patched or there is indeed a bug.
Try to patch a fresh unpatched Assembly-CSharp.dll and see if it changes anything.

Also if you could point out what data value in particular is bugged (Mind, Care, Stamina, etc.), it would help pinpointing the possible issue.

I will do some code digging and attempt to find any apparent issues.

**Comment by Algester** [comment]
I'm using Syballis version so I'm not sure how that is affected but will report later

**Comment by ghorsington** [comment]
I think I now understand what you mean.

Updated the original post with exact description.

Closed the issue because it was fixed in [`42401f6`](https://github.com/denikson/CM3D2.MaidFiddler/commit/42401f6affa5ea98149223794713c934def2956d).

**If a similar issue is encountered or if you originally meant another issue, open a new issue.**
